# Generated by Django 4.0.5 on 2022-06-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Nombre de Usuario')),
                ('email', models.CharField(max_length=30, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=30, verbose_name='Contraseña')),
                ('score', models.IntegerField(default=0, verbose_name='Puntuación')),
            ],
        ),
    ]
